name: nightly-neon-qt6

on:
  schedule:
    - cron: "52 23 * * *"
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DCMAKE_BUILD_TYPE=Debug
    -DWITH_QT6=ON

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://kdeneon/plasma:unstable
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "prepare env"
        uses: calamares/actions/prepare-neon@v4
      - name: "prepare source"
        uses: calamares/actions/generic-checkout@v4
      - name: "build"
        id: build
        uses: calamares/actions/generic-build@v4
      - name: "Calamares: archive"
        working-directory: ${{ env.BUILDDIR }}
        run: |
          make install DESTDIR=${{ env.BUILDDIR }}/stage
          tar czf calamares.tar.gz stage
      - name: "Calamares: upload"
        uses: actions/upload-artifact@v2
        with:
          name: calamares-tarball
          path: ${{ env.BUILDDIR }}/calamares.tar.gz
          if-no-files-found: error
          retention-days: 7
