name: nightly-opensuse-qt6

on:
  schedule:
    - cron: "32 2 * * *"
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DCMAKE_BUILD_TYPE=Debug
    -DWITH_QT6=ON

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://opensuse/tumbleweed
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "prepare env"
        shell: bash
        run: |
          # Add a Qt6/KF6 repo
          zypper --non-interactive addrepo -G https://download.opensuse.org/repositories/home:krop:kf6/openSUSE_Tumbleweed/home:krop:kf6.repo
          zypper --non-interactive refresh
          zypper --non-interactive up
          zypper --non-interactive in git-core jq curl
          # From deploycala.py
          zypper --non-interactive in bison flex git make cmake gcc-c++
          zypper --non-interactive in yaml-cpp-devel libpwquality-devel parted-devel python-devel libboost_headers-devel libboost_python3-devel
          zypper --non-interactive in libicu-devel libatasmart-devel
          # Qt6/KF6 dependencies
          zypper --non-interactive in qt6-concurrent-devel qt6-gui-devel qt6-linguist-devel qt6-network-devel qt6-svg-devel qt6-declarative-devel
          zypper --non-interactive in kf6-kcoreaddons-devel kf6-kdbusaddons-devel kf6-kcrash-devel
          zypper --non-interactive in libpolkit-qt6-1-devel
      - name: "prepare source"
        uses: calamares/actions/generic-checkout@v4
      - name: "build"
        id: build
        uses: calamares/actions/generic-build@v4
      - name: "notify: ok"
        if: ${{ success() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            OK ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git-summary }}
      - name: "notify: fail"
        if: ${{ failure() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: |
            FAIL ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git-summary }}
